ARG GPU_SUFFIX=''
ARG FROM_VERSION
FROM docker.h2o.ai/opsh2oai/h2o-3/dev-base${GPU_SUFFIX}:${FROM_VERSION}

COPY scripts/install_java_version /tmp
ENV JAVA_VERSION=8
RUN \
    chmod +x /tmp/install_java_version && \
    sync && \
    /tmp/install_java_version ${JAVA_VERSION} && \
    rm /tmp/install_java_version && \
    activate_java_${JAVA_VERSION} && \
    chmod a+w /usr/lib/jvm/

ENV \
  JAVA_HOME=/usr/lib/jvm/java-current-oracle \
  PATH=/usr/lib/jvm/java-current-oracle/bin:${PATH}
