ARG GPU_SUFFIX=''
ARG FROM_VERSION
FROM docker.h2o.ai/opsh2oai/h2o-3/dev-jdk-8-base${GPU_SUFFIX}:${FROM_VERSION}

RUN \
    echo "deb http://cran.mtu.edu/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list.d/cran.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9 && \
    apt-get update && \
    apt-get -y build-dep r-base && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/cache/apt/*

COPY scripts/install_R_version /tmp/
RUN \
    chmod a+x /tmp/install_R_version
